CREATE OR REPLACE TABLE USERS (
  USER_ID STRING PRIMARY KEY,
  EMAIL STRING UNIQUE,
  PASSWORD_HASH STRING,
  FULL_NAME STRING,
  PHONE_NUMBER STRING,
  ROLE STRING,
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE CLIENTS (
  CLIENT_ID STRING PRIMARY KEY,
  FULL_NAME STRING,
  EMAIL STRING,
  PHONE STRING,
  DEFAULT_LOCATION STRING,
  PROPERTY_TYPE STRING,
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE CONTRACTORS (
  CONTRACTOR_ID STRING PRIMARY KEY,
  FULL_NAME STRING,
  BUSINESS_NAME STRING,
  LICENSE_ID STRING,
  CORPORATION_ID STRING,
  INSURANCE_VERIFIED BOOLEAN DEFAULT FALSE,
  TIER STRING DEFAULT 'Basic',
  SERVICE_CATEGORY STRING,
  SERVICE_RANGE_KM NUMBER DEFAULT 25,
  LOCATION STRING,
  RATING_AVERAGE FLOAT DEFAULT 0,
  FIVE_STAR_REVIEW_COUNT NUMBER DEFAULT 0,
  ACCEPTED_REQUESTS NUMBER DEFAULT 0,
  TOTAL_REQUESTS_PINGED NUMBER DEFAULT 0,
  AVAILABILITY_STATUS STRING DEFAULT 'Available',
  ACTIVE_STATUS STRING DEFAULT 'Active',
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE SERVICE_REQUESTS (
  REQUEST_ID STRING PRIMARY KEY,
  CLIENT_ID STRING,
  RAW_CLIENT_MESSAGE STRING,
  GEMINI_STRUCTURED_OUTPUT VARIANT,
  SERVICE_CATEGORY STRING,
  PROBLEM_SUMMARY STRING,
  URGENCY STRING,
  RECOMMENDED_TIER STRING,
  SELECTED_TIER STRING,
  LOCATION STRING,
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE BOOKINGS (
  BOOKING_ID STRING PRIMARY KEY,
  REQUEST_ID STRING,
  CLIENT_ID STRING,
  CONTRACTOR_ID STRING,
  SERVICE_CATEGORY STRING,
  TIER_SELECTED STRING,
  PROBLEM_SUMMARY STRING,
  URGENCY STRING,
  STATUS STRING,
  SCHEDULED_WINDOW STRING,
  PREMIUM_COVERAGE BOOLEAN,
  REFUND_STATUS STRING,
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
  COMPLETED_AT TIMESTAMP
);

CREATE OR REPLACE TABLE REVIEWS (
  REVIEW_ID STRING PRIMARY KEY,
  BOOKING_ID STRING,
  CLIENT_ID STRING,
  CONTRACTOR_ID STRING,
  RATING NUMBER,
  REVIEW_TEXT STRING,
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE DISPATCH_EVENTS (
  EVENT_ID STRING PRIMARY KEY,
  REQUEST_ID STRING,
  BOOKING_ID STRING,
  CONTRACTOR_ID STRING,
  EVENT_TYPE STRING,
  EVENT_DETAILS VARIANT,
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);
